[package]
name = "ray_tracer_simple_image"
version = "0.1.0"
authors = ["projektir <oprojektir@gmail.com>"]

[dependencies]
serde = "1.0.7"
serde_json = "1.0.2"
serde_derive = "1.0.7"
image = "0.13.0"
